### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Syrest123** [MicroBioGenoHub/HIV-DRIVES#1]
Hello team
Thank you for the pipeline 
But I run all the code and at the end I call HIV-DRIVES and it says command not found.
Also I have activated the new HIV-DRIVES environment and its still the same thing
Power was on and off but i restarted downloading and still it failed.
Please help

 2011 cd && git clone https://github.com/MicroBioGenoHub/HIV-DRIVES.git
 2012  ls
 2013  cd HIV-DRIVES/
 2014  ls
 2015  conda env create -n HIV-DRIVES --file HIV-DRIVES-1.0-Linux-Installer.yml
 2016  bash setup.sh
 2017  ls
 2018  rm GRCh38_noalt_as.zip
 2019  ls
 2020  bash setup.sh
 2021  ls
 2022  rm GRCh38_noalt_as.zip
 2023  bash setup.sh
 2024  ls
 2025  cd ..
 2026  ls
 2027  bash clean.sh
 2028  ls
 2029  rm clean.sh
 2030  ls
 2031  conda activate HIV-DRIVES
 2032  HIV-DRIVES

**Comment by Kanyerezi30** [comment]
Hello Syrus

Could you let us know which operating system you are using?

In addition, try the commands below and send us the output

`source ~/.bashrc; echo $PATH`

**Comment by Syrest123** [comment]
I am running linux on widows using WSL 
I removed the previous environment created and repeated installing with a better internet connection.
The good thing it retries downloading when running the **_bash setup.sh_** command 
I think the issue was about my internet so the 3.5GB download was interrupted.
Thank you Steven 
Happy new year

**Comment by Kanyerezi30** [comment]
Glad that you found your way out
